label: 'ELIXIR Genome Beacons'
tagline: 'A Driver Project of the Global Alliance for Genomics and Health'
description: |
  Beacon is an open standard for genomics data discovery, developed by members of the Global Alliance for Genomics & Health
keywords: genomics, cloud, Beacon, DNA, sharing, ELIXIR, GA4GH
site_domain_name: beacon-project.io
url: 'https://schemablocks.org'
baseurl: ""
site_parent_link: 'https://www.elixir-europe.org/about-us/implementation-studies/beacons'
github_organisation: ga4gh-beacon
show_downloads: true
future: true

# instructions for processing specific directories

include:
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

collections_dir: pages
collections:
  general:
    output: true
    permalink: /general/:path/
  events:
    output: true
    permalink: /events/:path/
  people:
    output: true
    permalink: /people/:path/
  howto:
    output: true
    permalink: /howto/:path/
  specification:
    output: true
    permalink: /specification/:path/
  minutes:
    output: true
    permalink: /minutes/:path/

# navigation blocks can be used to separate different categories and add e.g. 
# external link block(s), in combination with a properly modified layout

nav_cat_blocks:
  General: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

General:
  about: 'About...'
  news: 'News & Press'
  people: Contributors
  events: Events
  howto: 'Examples, Guides & FAQ'
  specification: Specification
  roadmap: Roadmap
  network: 'Beacon Networks'
  minutes: Meeting Minutes
  contact: Contacts

categories_year_sorted:
  - news
  - minutes
  - events

tags_year_sorted:
  - releases
  - press
  - versions

related_sites:
  'Beacon @ ELIXIR': 'http://www.elixir-europe.org/about-us/implementation-studies/beacons'
  GA4GH: 'http://ga4gh.org'
  'Beacon<span style="color: red; font-weight: 800;">+</span>': 'http://beacon.progenetix.org'
  'beacon-network.org': 'http://beacon-network.org'
  'GA4GH::SchemaBlocks': 'http://schemablocks.org'
  'GA4GH::Discovery': 'http://ga4gh-discovery.github.io'
  'GA4GH::CLP': 'http://ga4gh-cp.github.io'
  'GA4GH::GKS': 'http://ga4gh-gks.github.io'

github_projects:
  'ELIXIR Beacon': 'http://github.com/ga4gh-beacon/'
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'
  
# tag_cloud items

cloud_tags:
  - admin
  - code
  - contacts
  - definitions
  - developers
  - development
  - FAQ
  - leads
  - minutes
  - network
  - press
  - proposal
  - queries
  - releases
  - specification
  - team
  - versions
  - website

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
navigation_max_items: 4 # number of shown links in current category
emptyArray: []          # dummy element for array initialisation


